server:
  port: 20201
spring:
  datasource:
    url: jdbc:mysql://192.168.204.110:3306/test_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    host: 192.168.204.110
    password: admin
    username: admin
    virtual-host: /
    port: 5672
    #开启手动ack机制，让程序去控制MQ消息的重发和删除及转移
    listener:
      direct:
        acknowledge-mode: manual
        retry:
          enabled: true   #开启重试
          max-attempts: 3 #最大重试次数
          initial-interval: 1000ms #重试间隔时间
    #集群连接方式
    #addresses: 192.168.204.30:5672,192.168.204.30:5673
    # 配置rabbitMQ消息确认
    publisher-confirm-type: correlated


#springboot。rabbitmq.publisher-confirms 新版本已经弃用，现在使用的时springboot。rabbitmq.publisher-confirms-type
# NONE 是禁用发布确认模式，是默认值
# correlated 是生产者在投递消息的时候如果消息发送到队列中，会触发回调确认方法
#logging:
#  level:
#    root: debug
